server:
  port: 9000

resilience4j:
  circuitbreaker:
    enabled: true
    instances:
      customer-profile-api:
        failureRateThreshold: 50

config:
  customer-profile-api:
    url: http://localhost:8080/